# Generated by Django 5.0.6 on 2024-05-22 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_contactnumber_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactnumber',
            name='contact',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.person'),
        ),
    ]
