# Generated by Django 5.0.6 on 2024-05-22 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_contact_contactnumber_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnumber',
            name='person',
            field=models.ForeignKey(default='--------', on_delete=django.db.models.deletion.CASCADE, to='app.person'),
        ),
    ]
